### ISSUE TITLE
deprecated, undefinded v7

### ISSUE THREAD

**Issue by Lechus** [cfortune/PHP-Bounce-Handler#1]
Function split() is deprecated,

Undefined index: Received
Location:bounce_driver.class.php on line 412

Undefined index: X-loop

Use of undefined constant boundary - assumed 'boundary' - line405
Undefined index: Feedback-type line269
Undefined index: Received line453

**Comment by cfortune** [comment]
out of date codebase.  (will update soon _sigh_).

http://anti-spam-man.com/php_bouncehandler/

**Comment by Lechus** [comment]
v7 from http://anti-spam-man.com/php_bouncehandler/
bounce_driver.class.php 33KB    Mar 11 2011 05:33:36 PM
has the same out-of-date code.
