### ISSUE TITLE
undefinded v7.3 

### ISSUE THREAD

**Issue by Lechus** [cfortune/PHP-Bounce-Handler#2]
in testdriver.php add: ini_set('display_errors', 'On');

Iam using php framework Laravel 3.2.x with error display on.
I get:
Message:

Undefined variable: autorespondlist
Location:

bounce_driver.class.php on line 85

because of Problematic last line which is utf encoded.  ...#163.com

After removing that line there is next error:

Undefined index: Subject
Location: bounce_driver.class.php on line 455

Notice: Undefined index: per_recipient in bounce_driver.class.php on line 477

should be ['boundary'] in:
function is_RFC1892_multipart_report(){
        return @$this->head_hash['Content-type']['type']=='multipart/report'
           &&  @$this->head_hash['Content-type']['report-type']=='delivery-status'
           &&  @$this->head_hash['Content-type'][boundary]!=='';

**Comment by cfortune** [comment]
error_reporting(0);// turn off PHP Notices
