### ISSUE TITLE
How to use with php_imap?

### ISSUE THREAD

**Issue by alexckent** [cfortune/PHP-Bounce-Handler#5]
Hello,

As far as I can see, this class uses the raw source of an email to work out whether it's a bounce or not.

Is it possible to use this class with php_imap which doesn't return the raw source of a message?

Something like the following, but obviously imap_body only returns the body and not the whole message:

```
    $body = imap_body($mbox, $i);

$multi_array = $bouncehandler->get_the_facts($body);

var_export($multi_array);
```

Any tips or pointers would be appreciated.

Thanks,

Alex

**Comment by cfortune** [comment]
http://www.php.net/manual/en/function.imap-fetchheader.php
$header = imap_fetchheader ($mbox, $i);

Chris Fortune
LAMP Programmer
Seafoam Media, LLC
seafoammedia.com

**Comment by alexckent** [comment]
Hi Chris,

Thanks for the tip. This did the job:

$src = imap_fetchheader($mbox, $i).PHP_EOL.imap_body($mbox, $i);
$multi_array = $bouncehandler->get_the_facts($src);

:)

Alex
